# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '1.105.2'

default_platform :ios

platform :ios do
  before_all do
    # ENV['SLACK_URL'] = 'https://hooks.slack.com/services/...'
    cocoapods
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  desc 'Submit a new Beta Build to Crashlytics'
  lane :beta do
    # Ensure that there that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number (not the version number)
    increment_build_number
    # match(type: 'appstore') # more information: https://codesigning.guide
    gym(scheme: 'Chisto', use_legacy_build_api: true) # Build your app - more options available
    # Upload to Crashlytics
    crashlytics
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  lane :testflight do
    # Ensure that there that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number (not the version number)
    increment_build_number
    # match(type: 'appstore') # more information: https://codesigning.guide
    gym(scheme: 'Chisto')
    # Upload to Testflight
    pilot(skip_waiting_for_build_processing: true)
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    # match(type: 'appstore')
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: 'Successfully deployed new App Update.'
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
