# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.22.0'

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  desc 'Submit a new Beta Build to Crashlytics'
  lane :beta do
    # Ensure that there that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number (not the version number)
    increment_build_number
    # Manage code signing
    match(type: 'development')
    # Build your app - more options available
    gym(scheme: 'Chisto')
    # Upload to Crashlytics
    crashlytics(groups: ['chisto-dev'])
  end

  desc 'Submit a new Beta Build to TestFlight'
  lane :release do
    # Ensure that there that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number (not the version number)
    increment_build_number
    # Manage code signing
    match(type: 'appstore')
    # Build your app - more options available
    gym(scheme: 'Chisto', include_bitcode: true)
    # Upload to Testflight
    pilot(skip_waiting_for_build_processing: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(message: 'Successfully deployed new App Update.')
  end

  error do |lane, exception|
    # slack(message: exception.message, success: false)
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
